apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basketapi.fullname" . }}-secrets
type: Opaque
data:
  ConnectionStrings__EventBus: {{ .Values.eventBus.connectionString | b64enc | quote }}
  ConnectionStrings__Redis: {{ .Values.redis.connectionString | b64enc | quote }}