apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orderingapi.fullname" . }}-secrets
type: Opaque
data:
  ConnectionStrings__EventBus: {{ .Values.eventBus.connectionString | b64enc | quote }}
  ConnectionStrings__OrderingDB: {{ .Values.db.connectionString | b64enc | quote }}