apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalogapi.fullname" . }}-secrets
type: Opaque
data:
  ConnectionStrings__EventBus: {{ .Values.eventBus.connectionString | b64enc | quote }}
  ConnectionStrings__CatalogDb: {{ .Values.db.connectionString | b64enc | quote }}